version: "2.3"

services:
  gitlab:
    restart: unless-stopped
    image: gitlab/gitlab-ce:10.6.4-ce.0
    container_name: gitlab
    hostname: gitlab.${MYDOMAIN}
    labels:
      - "traefik.frontend.rule=Host:gitlab.${MYDOMAIN}"
      - "traefik.port=80" 
    networks:
      - service
    volumes:
      - gitlab-etc:/etc/gitlab
      - gitlab-data:/var/opt/gitlab
      - gitlab-logs:/var/log/gitlab
    expose:
      - 80
      - 443
      - 22
      - 3222
    ports:
      - "3222:3222"
    environment:
      - GITLAB_OMNIBUS_CONFIG="external_url 'http://gitlab.${MYDOMAIN}/'; gitlab_rails['lfs_enabled'] = true; gitlab_rails['gitlab_shell_ssh_port'] = 3222 "
      - GITLAB_HOST_URL="https://gitlab.${MYDOMAIN}/"
      - GENERATED_EXTERNAL_URL="https://gitlab.${MYDOMAIN}/"
#    env_file:
#      - gitlab.env

volumes:
  gitlab-etc:
    driver: nfs
    driver_opts: 
      share: 172.17.0.1/srv/data/volumes/gitlab-etc
  gitlab-data:
    driver: nfs
    driver_opts: 
      share: 172.17.0.1/srv/data/volumes/gitlab-data
  gitlab-logs:
    driver: nfs
    driver_opts: 
      share: 172.17.0.1/srv/data/volumes/gitlab-logs

networks:
  service:
    external:
      name: service

